<?php

$con=mysql_connect("localhost","root","");
mysql_select_db("regestration",$con);

if(isset($_POST['submit']))
	{
		$a=$_POST['regno'];

		$login=mysql_query("select * from regd where regdno='$a'");
		$row=mysql_fetch_array($login);
		     
			if(mysql_num_rows($login) !=0)

			{
				session_start();
				$_SESSION['Name']=$_POST['userid'];
				//header("location:complain.php");
				
// PHP permanent URL redirect - generated by www.rapidtables.com
header("Location:ban1.html", true, 301);
exit();

	//echo '<script>window.location="complain.php";</script>';
			}

			else
			{
				header("location:ban.php");
			}
	}

?>
