<?php
include 'mail/email.php'; // used to include email folder
	if(isset($_POST['submit'])){
   $from1 = $_POST['emailsignup'];
   }
	$email = '130301csr017@cutm.ac.in';
      $msg="
Dear   ,

      <p> Your password is : $password </p>
      <p> Copy this password and paste it in given password field.
      Click here  www.blogsarena.in/password-recovery-login.php to login.
      <p style='color:red;'>........this is a autogenerated mail don't reply to it........</p>";


$mail->From = $from1;//sender
$mail->FromName = "HostelManager"; // Name to indicate where the email came from when the recepient received
$mail->AddAddress($email);//receiver
$mail->WordWrap = 50; // set word wrap
$mail->IsHTML(true); // send as HTML
$mail->Subject = "Forgot Password-: "; //used for mail subject
$mail->Body =$msg; //HTML Body
if(!$mail->Send())
{
        //echo '<center>';
    //Slow internet try again       
}
else{
     // email has successfully sent.
  }
