<?php
session_start();
if(isset($_SESSION['Name']))
{
	header("location:complain.php");
}
else
{
?>


<!DOCTYPE html>
<html lang="en">
<head>
  <title>CUTM LIBRARY</title>
  	<meta charset="utf-8">
 	 <meta name="viewport" content="width=device-width, initial-scale=1">
 	 <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

 <center>
  <img src="uv25757.png" style="width:80px;height:80px"> 
   <img src="g-gif-update.gif" style="width:800px;height:80px">
 </center>

<hr size="3" color="green"> 
<div class="container-fluid">
  <center><h1><font face="Goudy Stout" size="5" color="blue"><i>CENTURION INSTITUTE OF TECNOLOGY AND MANAGEMENT </i></FONT></h1></center>
  <div class="row">
    <div class="col-sm-3 col-md-6 col-lg-4" style="background-color:transparent;">
      <p>


<marquee bgcolor="#000080" onMouseOver="this.scrollAmount=0" onMouseOut="this.scrollAmount=1" scrollamount="1" direction="up" loop="true" >
<center>
<font color="#ffffff" size="+1">CUTM MESS IMAGE</font><p>
<font color="#ff0000" size="+1"><img src="2.jpg" style="width:350px;height:150px"></font><p> 
<font color="#ffffff" size="+1"><img src="3.jpg" style="width:350px;height:150px"></font><p>
<font color="#ffffff" size="+1"><img src="4.jpg" style="width:350px;height:150px" ></font><p>


</font>
</center>
</marquee>






</p>
     
    </div>
   
<div class="col-sm-9 col-md-6 col-lg-8" style="background-color:lavenderblush;">
     <marquee bgcolor="#000080" onMouseOver="this.scrollAmount=0" onMouseOut="this.scrollAmount=1" scrollamount="2" direction="left" loop="true" >
<font color="#ffffff" size="+2">      
<p>
<img src="spinning-arrow-right.gif">
The canteen serves a variety of delicious and healthy dishes both for vegetarians as well as non vegetarians, at a minimal cost. The menu is regularly modified as per seasonal cycles and desired choices. There are student food committees formed to ensure the quality of the food and the cleanliness of the canteens.




</font></p>

      </font>
</center>
</marquee>
    </div>


 <div>
     
<CENTER>      
<p><img src="Food_Barnstar_Hires.png" style="width:140px;height:140px" ></font></p>

      
</center>
</marquee>
    </div>


<div class="col-sm-9 col-md-6 col-lg-8" style="background-color:lavenderblush;">
      <p>


<center>

<font face="" size="4" color="blue">
		<div id="register" class="animate form">
			<form  action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST" autocomplete="on"> 
				<h1> LOGIN YOUR ACCOUNT </h1> 
				<table>
				<tr>
                	<td>
               
						<label for="usernamesignup" class="uname" data-icon="u">Username</label>
                    </td>
                   	 <td>
							<input id="usernamesignup" name="userid" required type="text" placeholder="******* ********" />
					 </td>
                 </tr>
                 
                 
               
                  
                   
                   <tr>
                   	<td>
						<label for="passwordsignup_confirm" class="youpasswd" data-icon="p"> password </label>
                    </td>
                    <td>
					<input id="passwordsignup_confirm" name="password" required type="password" placeholder="eg. X8df!90EO"/>
				
               		 </td>
               	 </tr>
                
                <tr>
                <td>
				<p class="signin button"> 
					<input type="submit" name="submit" allign="left"/> 
				</p>
				</td>
                </tr>
                <tr>
                <td>
                <center>
                <a style="text-decoration:none" href="ban.html">Create an Account</a>
                </center>
                </td>
                </tr>
                </table>
			</form></center>

</p>
    </div>
</body>
</html>
<?php

$con=mysql_connect("localhost","root","");
mysql_select_db("regestration",$con);

if(isset($_POST['submit']))
	{
		$a=$_POST['userid'];
		$d=$_POST['password'];

		$login=mysql_query("select * from regd where Name='$a' and Password='$d'");
		$row=mysql_fetch_array($login);
		     
			if(mysql_num_rows($login) !=0)

			{
			
				$_SESSION['Name']=$_POST['userid'];
				//header("location:complain.php");
				
// PHP permanent URL redirect - generated by www.rapidtables.com
header("Location: complain.php", true, 301);
exit();

			}

			else
			{
				echo "invalid login";
			}
	}
}
?>
